### ISSUE TITLE
Plugin not working on version 42

### ISSUE THREAD

**Issue by xoche** [getflourish/Sketch-Style-Inventory#86]
Inventory --> Generate isn't working.

Is this plugin no longer maintained?

**Comment by getflourish** [comment]
Hi everyone. I finally spent some hours fixing the plugin and updated it to work in Sketch 49.3.

I also added support for automatic updates. This plugin does some heavy lifting and uses a lot of undocumented Sketch internals, so if you still run into issues, please keep reporting them. As you may have noticed, I didn’t maintain the plugin for a long time, simply because I personally didn’t find enough value in it anymore.

Thus, I’m actually curious to know what parts of the plugin are most valuable to you. I made this plugin a long time ago and I’m not sure anymore if it solves problems better than other plugins out there. I still use the selection commands quite a lot and I’m happy to see that Sketch finally has a "replace color" feature which this plugin originally had.
