### ISSUE TITLE
Can't Generate Inventory in Sketch 47.1

### ISSUE THREAD

**Issue by tresaping** [getflourish/Sketch-Style-Inventory#92]
Hi, I'm working with Sketch 47.1 and can't generate an inventory. 
A new page is created and a message says 'Please select an artboard. The inventory will be placed next to it.', but I can't generate an inventory. Could you help me out: What am I missing?

Thx in advance.

**Comment by xctisboss** [comment]
Having the same issues, nothing I tried worked so far.

**Comment by qmolee** [comment]
me too

**Comment by sjclark** [comment]
me three! <3

**Comment by RussellBishop** [comment]
This is sad :(

**Comment by getflourish** [comment]
Hi everyone. I finally spent some hours fixing the plugin and updated it to work in Sketch 49.3.

I also added support for automatic updates. This plugin does some heavy lifting and uses a lot of undocumented Sketch internals, so if you still run into issues, please keep reporting them. As you may have noticed, I didn’t maintain the plugin for a long time, simply because I personally didn’t find enough value in it anymore.

Thus, I’m actually curious to know what parts of the plugin are most valuable to you. I made this plugin a long time ago and I’m not sure anymore if it solves problems better than other plugins out there. I still use the selection commands quite a lot and I’m happy to see that Sketch finally has a "replace color" feature which this plugin originally had.
