### ISSUE TITLE
Doesn't seem to work in 47.1

### ISSUE THREAD

**Issue by moniquep** [getflourish/Sketch-Style-Inventory#93]

**Comment by dorian-grey** [comment]
Same here - guess this is dead? Last update 11 months ago? @getflourish

**Comment by xekushuna** [comment]
Any known alternatives to this?

**Comment by design2dev** [comment]
who made a working alternative?! this is a great plugin

**Comment by ziyafenn** [comment]
Still not working

**Comment by esmallwood** [comment]
maw

**Comment by AlexandraScheerman** [comment]
Hi guys, do you know any alternative. This plugin doesn't seem to work anymore

**Comment by ziyafenn** [comment]
Hey @AlexandraScheerman, unfortunately, there is only one alternative — [Craft Plugin](https://www.invisionapp.com/craft), which is not exactly the same but might be helpful.

**Comment by moniquep** [comment]
Yeah agreed. Craft plugin and hitting shift + command + C will generate a style inventory

**Comment by florianginetta** [comment]
Hi everyone. I finally spent some hours fixing the plugin and updated it to work in Sketch 49.3. 

I also added support for automatic updates. This plugin does some heavy lifting and uses a lot of undocumented Sketch internals, so if you still run into issues, please keep reporting them. As you may have noticed, I didn’t maintain the plugin for a long time, simply because I personally didn’t find enough value in it anymore.

Thus, I’m actually curious to know what parts of the plugin are most valuable to you. I made this plugin a long time ago and I’m not sure anymore if it solves problems better than other plugins out there. I still use the selection commands quite a lot and I’m happy to see that Sketch finally has a "replace color" feature which this plugin originally had.

**Comment by getflourish** [comment]
Hi everyone. I finally spent some hours fixing the plugin and updated it to work in Sketch 49.3.

I also added support for automatic updates. This plugin does some heavy lifting and uses a lot of undocumented Sketch internals, so if you still run into issues, please keep reporting them. As you may have noticed, I didn’t maintain the plugin for a long time, simply because I personally didn’t find enough value in it anymore.

Thus, I’m actually curious to know what parts of the plugin are most valuable to you. I made this plugin a long time ago and I’m not sure anymore if it solves problems better than other plugins out there. I still use the selection commands quite a lot and I’m happy to see that Sketch finally has a "replace color" feature which this plugin originally had.
